name: gitpages_workflow
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: mkdocs build
<<<<<<<< HEAD:.github/workflows/gitpages_workflow.yml
      - run: mkdocs gh-deploy --force
========
      - run: mkdocs gh-deploy --force
>>>>>>>> 2b40c2cf7588cb028aa4b1803059bec5467138b3:.github/workflows/ci.yml
